mysite/bookends/urls.py
from django.shortcuts import render
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'bookends'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    url(r'^home/', views.HomeViewFunction),
    url(r'^payments/', views.PaymentsViewFunction),
    url(r'^login/', views.LoginViewFunction),
    url(r'^paymentstest/', views.PaymentsTestViewFunction),
    url(r'^books/', views.BooksViewFunction),
    url(r'^works/', views.WorksViewFunction),
    #path(r'^books/', views.BooksView.as_view(), name='books'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookends/', include('bookends.urls')),
]

mysite/bookends/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

class Addresses(models.Model):
    shippingaddress = models.CharField(db_column='ShippingAddress', primary_key=True, max_length=50)  # Field name made lowercase.
    stateprovince = models.CharField(db_column='StateProvince', max_length=40, blank=True, null=True)  # Field name made lowercase.
    country = models.CharField(db_column='Country', max_length=60, blank=True, null=True)  # Field name made lowercase.
    city = models.CharField(db_column='City', max_length=30, blank=True, null=True)  # Field name made lowercase.
    surveyid = models.IntegerField(db_column='SurveyID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'addresses'


class Books(models.Model):
    bookid = models.IntegerField(db_column='BookID', primary_key=True)  # Field name made lowercase.
    available = models.IntegerField(db_column='Available', blank=True, null=True)  # Field name made lowercase.
    location = models.CharField(db_column='Location', max_length=40, blank=True, null=True)  # Field name made lowercase.
    isbn = models.CharField(db_column='ISBN', max_length=13, blank=True, null=True)  # Field name made lowercase.
    requestid = models.IntegerField(db_column='RequestID', blank=True, null=True)  # Field name made lowercase.
    donationid = models.IntegerField(db_column='DonationID', blank=True, null=True)  # Field name made lowercase.
	
    class Meta:
        managed = False
        db_table = 'books'



class Children(models.Model):
    childid = models.IntegerField(db_column='ChildID', primary_key=True)  # Field name made lowercase.
    readinglevel = models.CharField(db_column='ReadingLevel', max_length=40, blank=True, null=True)  # Field name made lowercase.
    interests = models.CharField(db_column='Interests', max_length=50, blank=True, null=True)  # Field name made lowercase.
    clientid = models.IntegerField(db_column='ClientID', blank=True, null=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=50, blank=True, null=True)  # Field name made lowercase.
    age = models.IntegerField(db_column='Age', blank=True, null=True)  # Field name made lowercase.
    surveyid = models.IntegerField(db_column='SurveyID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'children'


class Clients(models.Model):
    clientid = models.IntegerField(db_column='ClientID', primary_key=True)  # Field name made lowercase.
    requestid = models.ForeignKey('Requests', models.DO_NOTHING, db_column='RequestID', blank=True, null=True)  # Field name made lowercase.
    username = models.CharField(db_column='Username', max_length=50, blank=True, null=True)  # Field name made lowercase.
    password = models.CharField(db_column='Password', max_length=30, blank=True, null=True)  # Field name made lowercase.
    personid = models.IntegerField(db_column='PersonID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'clients'


class Donations(models.Model):
    donationid = models.IntegerField(db_column='DonationID', primary_key=True)  # Field name made lowercase.
    amount = models.FloatField(db_column='Amount', blank=True, null=True)  # Field name made lowercase.
    method = models.CharField(db_column='Method', max_length=20, blank=True, null=True)  # Field name made lowercase.
    donationdate = models.DateField(db_column='DonationDate', blank=True, null=True)  # Field name made lowercase.
    taxreceipt = models.CharField(db_column='TaxReceipt', max_length=40, blank=True, null=True)  # Field name made lowercase.
    donorid = models.IntegerField(db_column='DonorID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'donations'


class Donors(models.Model):
    donorid = models.IntegerField(db_column='DonorID', primary_key=True)  # Field name made lowercase.
    personid = models.IntegerField(db_column='PersonID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'donors'


class Payments(models.Model):
    amountreceived = models.FloatField(db_column='AmountReceived', primary_key=True)  # Field name made lowercase.
    datepaid = models.DateField(db_column='DatePaid')  # Field name made lowercase.
    method = models.CharField(db_column='Method', max_length=20, blank=True, null=True)  # Field name made lowercase.
    clientid = models.IntegerField(db_column='ClientID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'payments'
        unique_together = (('amountreceived', 'datepaid', 'clientid'),)


class People(models.Model):
    personid = models.IntegerField(db_column='PersonID', primary_key=True)  # Field name made lowercase.
    address = models.CharField(db_column='Address', max_length=100, blank=True, null=True)  # Field name made lowercase.
    firstname = models.CharField(db_column='FirstName', max_length=20, blank=True, null=True)  # Field name made lowercase.
    lastname = models.CharField(db_column='LastName', max_length=20, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=60, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'people'


class Requestdetails(models.Model):
    requestid = models.IntegerField(db_column='RequestID', primary_key=True)  # Field name made lowercase.
    requestcost = models.IntegerField(db_column='RequestCost', blank=True, null=True)  # Field name made lowercase.
    dateshipped = models.DateField(db_column='DateShipped', blank=True, null=True)  # Field name made lowercase.
    pullsheet = models.CharField(db_column='PullSheet', max_length=200, blank=True, null=True)  # Field name made lowercase.
    boxesrequested = models.IntegerField(db_column='BoxesRequested', blank=True, null=True)  # Field name made lowercase.
    datebookspulled = models.DateField(db_column='DateBooksPulled', blank=True, null=True)  # Field name made lowercase.
    datearrived = models.DateField(db_column='DateArrived', blank=True, null=True)  # Field name made lowercase.
    shippingmethod = models.CharField(db_column='ShippingMethod', max_length=20, blank=True, null=True)  # Field name made lowercase.
    shippingcost = models.FloatField(db_column='ShippingCost', blank=True, null=True)  # Field name made lowercase.
    requestcomplete = models.IntegerField(db_column='RequestComplete', blank=True, null=True)  # Field name made lowercase.
    surveycomplete = models.IntegerField(db_column='SurveyComplete', blank=True, null=True)  # Field name made lowercase.
    amountowed = models.FloatField(db_column='AmountOwed', blank=True, null=True)  # Field name made lowercase.
    paymentcomplete = models.IntegerField(db_column='PaymentComplete', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'requestdetails'


class Requests(models.Model):
    requestid = models.IntegerField(db_column='RequestID', primary_key=True)  # Field name made lowercase.
    datemade = models.DateField(db_column='DateMade', blank=True, null=True)  # Field name made lowercase.
    totalbooksrequested = models.IntegerField(db_column='TotalBooksRequested', blank=True, null=True)  # Field name made lowercase.
    clientid = models.IntegerField(db_column='ClientID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'requests'


class Staff(models.Model):
    staffid = models.IntegerField(db_column='StaffID', primary_key=True)  # Field name made lowercase.
    role = models.CharField(db_column='Role', max_length=50, blank=True, null=True)  # Field name made lowercase.
    personid = models.IntegerField(db_column='PersonID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'staff'


class Surveys(models.Model):
    surveyid = models.IntegerField(db_column='SurveyID', primary_key=True)  # Field name made lowercase.
    homeschooled = models.CharField(db_column='HomeSchooled', max_length=5, blank=True, null=True)  # Field name made lowercase.
    surveydate = models.DateField(db_column='SurveyDate', blank=True, null=True)  # Field name made lowercase.
    howdidyouhearaboutus = models.CharField(db_column='HowDidYouHearAboutUs', max_length=100, blank=True, null=True)  # Field name made lowercase.
    clientid = models.IntegerField(db_column='ClientID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'surveys'


class Works(models.Model):
    isbn = models.CharField(db_column='ISBN', primary_key=True, max_length=13)  # Field name made lowercase.
    genre = models.CharField(db_column='Genre', max_length=40, blank=True, null=True)  # Field name made lowercase.
    author = models.CharField(db_column='Author', max_length=40, blank=True, null=True)  # Field name made lowercase.
    title = models.CharField(db_column='Title', max_length=50, blank=True, null=True)  # Field name made lowercase.

mysite/bookends/forms.py
from django import forms

class NameForm(forms.Form):
	your_name = forms.CharField(label='Your name', max_length=100)

mysite/bookends/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic


from .forms import NameForm
from .models import Question, Choice, Books, Works

# Create your views here

def HomeViewFunction(request):
    return render(request, 'bookends/home.html')

def PaymentsViewFunction(request):
    return render(request, 'bookends/payments.html')

def LoginViewFunction(request):
    return render(request, 'bookends/login.html')

def PaymentsTestViewFunction(request):
    template_name = 'bookends/books.html'
    context_object_name = 'all_books'
    
    def get_queryset(self):
        """Return the last five published questions."""
        return Books.objects.order_by('title')
    return render(request, 'bookends/payments_form.html')

def BooksViewFunction(request):
    template_name = 'bookends/books.html'
    books_list = Books.objects.all()
    works_list = Works.objects.all()
    return render(request, 'bookends/books.html', {'books': books_list, 'works': works_list})

def WorksViewFunction(request):
    template_name = 'bookends/works.html'
    books_list = Books.objects.all()
    works_list = Works.objects.all()
    return render(request, 'bookends/works.html', {'books': books_list, 'works': works_list})

def WorksDB(request):
    works_list = Works.objects.order_by('isbn')[:10]
    return render(request, 'bookends/worksDB.html', {'works': works_list})

def BooksDB(request):
    books_list = Books.objects.order_by('isbn')[:10]
    return render(request, 'bookends/booksDB.html', {'books': books_list})

class HomeView(generic.ListView):
    template_name='bookends/home.html'

class IndexView(generic.ListView):
    template_name = 'bookends/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class BooksView(generic.ListView):
    template_name = 'bookends/books.html'
    context_object_name = 'all_books'
    
    def get_queryset(self):
        """Return the last five published questions."""
        return Books.objects.order_by('title')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'bookends/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'bookends/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'bookends/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('bookends:results', args=(question.id,)))
def payments(request):
    return HttpResponseRedirect(reverse('bookends:results'))
def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm()

    return render(request, 'name.html', {'form': form})

mysite/bookends/templates/bookends/books.html
  
 
 
<!doctype html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

 
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
<meta name="generator" content="Jekyll v3.8.6">
<title>Jumbotron Template · Bootstrap</title>
 
 
<link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/jumbotron/">
 
 
<!-- Bootstrap core CSS -->
<link href="/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 
 
<!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">
 
 
 
 
<style>
.bd-placeholder-img {
font-size: 1.125rem;
text-anchor: middle;
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
}
 
 
@media (min-width: 768px) {
.bd-placeholder-img-lg {
font-size: 3.5rem;
}
}
</style>
<!-- Custom styles for this template -->
<link href="jumbotron.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
<a class="navbar-brand" href="../home/">Bookends</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
 
 
<div class="collapse navbar-collapse" id="navbarsExampleDefault">
<ul class="navbar-nav mr-auto">
<li class="nav-item active">
<a class="nav-link" href="../home/">Home <span class="sr-only">(current)</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">Link</a>
</li>
<li class="nav-item">
<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
<div class="dropdown-menu" aria-labelledby="dropdown01">
<a class="dropdown-item" href="#">Action</a>
<a class="dropdown-item" href="#">Another action</a>
<a class="dropdown-item" href="#">Something else here</a>
</div>
</li>
</ul>
<form class="form-inline my-2 my-lg-0">
<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
</div>
</nav>
 
 
<main role="main">
 
 
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron" style="background-color:#fbe327">
    <div class="container">
        <h1 class="display-3">Welcome to the Library!</h1>
        <p>Browse Books Here and Add Them to your Cart</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Login &raquo;</a></p>
    </div>
</div>
 
 
<h3>Our Library</h3>

{% if books %}
    <ul>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Select Book</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">ISBN</th>
                <th scope="col">Location</th>
                <th scope="col">Available</th>
                <th scope="col">Picture</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
	
                <tr>
                    <td scope="row"> <!-- Default unchecked --> <div class="custom-control custom-checkbox"> <input type="checkbox" class="custom-control-input" id="tableDefaultCheck3"> </div> </td>
                    <td id="title"></td>
                    <td id="author"></td>
                    <td id=isbnid>{{ book.isbn }}</td>
                    <td>{{ book.location }}</td>
                    <td>{{ book.available }}</td>
                    <td id="imagehere"></td>

                    <script type="text/javascript">
                        var isbnjs = {{ book.isbn}};
                        isbnjs = isbnjs.toString();
                        console.log(isbnjs);
                        console.log(typeof(isbnjs));
                        var url='';
                        var img='';
                        var title='';
                        var author='';
                
                        $.get("https://www.googleapis.com/books/v1/volumes?q=" + isbnjs, function(response){
                            console.log("inside api response");
                
                            for(i=0;i<1;i++){
                                title=$('<p>' + response.items[i].volumeInfo.title + '</p>')
                                author=$('<h5 class="center-align white-text">' + response.items[i].volumeInfo.authors + '</h5>')
                                img=$('<img class="card z-depth-5" id="dynamic"><br><a href=' + response.items[i].volumeInfo.infoLink + '><button id="imagebutton">Read More</button></a>');
                                url= response.items[i].volumeInfo.imageLinks.thumbnail;
                                img.attr('src', url);
                                title.appendTo("#title");
                                author.appendTo("#author");
                                img.appendTo("#imagehere");
                
                            }
                        });
                        isbnjs = null;
                    </script>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </ul>
 
 
{% else %}
    <p>No books are available.</p>
{% endif %} 

mysite/bookends/templates/bookends/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'bookends:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

<div id="search">
    <form id="myform">
        <a href="#" onclick="document.forms['myform'].submit();">Call Form</a>
        <div class="input-field">
            <input type="search" id="books">
            <label for="search">Search Books</label>
        </div>
        <button type="submit">Search Books</button>
    </form>
</div>

<div id="result">

</div>

    <label for="isbn">Your name: </label>
    <input id="isbn" type="search" name="isbn" value="{{ current_name }}">
    <input name="formSubmitIndex" type="submit" value="OK">

<button id="about-btn"> Click Me - I'm Javascript on Speed</button>

    
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!--script src="polls/statics/js/search.js"></script-->
<script type="text/javascript">
    $(document).ready(function(){
        console.log("after document");
        $("#myform".submit(function(){
            console.log("after submit");
            var search = $("#books").val();
            if(search == ''){
                alert("Please enter something in the field.");
            }
            else{
                var url='';
                var img='';
                var title='';
                var author='';
    
                $.get("https://www.googleapis.com/books/v1/volumes?q=" + search, function(response){
                    console.log(response);
    
                    for(i=0;i<response.items.length;i++){
                        title=$('<h5 class="center-align white-text">' + response.items[i].volumeInfo.title + '</h5>')
                        author=$('<h5 class="center-align white-text">' + response.items[i].volumeInfo.authors + '</h5>')
                        img=$('<img class="card z-depth-5" id="dynamic">');
    
                    }
                });
            }
        }));
        $("#about-btn").click( function(event) {
            alert("You clicked the button using JQuery!");
        });
        return false;
    });
</script>

mysite/bookends/templates/bookends/index.html
<a href="/bookends/home">click here for the home page!</a>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/bookends/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/bookends/templates/bookends/payments_form.html
<h3>Payment Test Page</h3>
{% load crispy_forms_tags %}

{% block content %}
<form action="/bookends/payments/" method="post">
    {% csrf_token %}
    <h5>inside form</h3>
    {% include "bookends/payments.html" %}

    <a href="/bookends/payments">{{ payments.html }}</a>

    {{ Payments.method }}
    <div class="form-group">
        {{ payments.amountreceived }}
    </div>
    <div class="form-group">
        {{ payments.datepaid }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

mysite/bookends/templates/bookends/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'bookends:detail' question.id %}">Vote again?</a>